### PR TITLE
Change STRK and ETH ERC20 implementation; fix minting

### LINKED ISSUE #795: Problem with default erc20 class
**Describe the bug (observed vs expected behavior)**

The class hashes of  STRK and ETH tokens are not the ones used in Testnet/Mainnet. These token are using in fact the `0x46ded64ae2dead6448e247234bab192a9c483644395b66f2155f2614e5804b0` class (this class exists in Testnet).
If I use Starknet.js to read the constructor of this class in Devnet, I have :
```
{
  type: 'constructor',
  name: 'constructor',
  inputs: [
    {
      name: 'owner',
      type: 'core::starknet::contract_address::ContractAddress'
    }
  ]
}
```
 If I read the constructor of the same class in Testnet, I have :
```
{
  type: 'constructor',
  name: 'constructor',
  inputs: [
    { name: 'name', type: 'core::felt252' },
    { name: 'symbol', type: 'core::felt252' },
    { name: 'fixed_supply', type: 'core::integer::u256' },
    {
      name: 'recipient',
      type: 'core::starknet::contract_address::ContractAddress'
    }
  ]
}
```
We have here a problem: a same class hash can't use different constructors.
The class hash has been forced in devnet, and is generating troubles.

To have the same behavior than Testnet, a good solution could be to use the same classes for STRK & ETH than in Testnet/devnet:
- STRK : proxy class `0x009524a94b41c4440a16fd96d7c1ef6ad6f44c1c013e96662734502cd4ee9b1f` with implementation class `0x06e7226605869c2bd8cb86a647b451adc0b90e1e4f00b1c45d502dcd2ba6d41e`
- ETH : class `0x076791ef97c042f81fbf352ad95f39a22554ee8d7927b2ce3c681f3418b5206a`

**Not reproducible on testnet**

- [x] This issue is only present on Devnet and cannot be reproduced on the alpha-sepolia testnet (check the box if true).

**Steps to reproduce the behavior**

1. cargo run --release -- --seed 0  --state-archive-capacity full --lite-mode
2.
```ts
const classHash = "0x46ded64ae2dead6448e247234bab192a9c483644395b66f2155f2614e5804b0"; 
const compiledSierra = await myProvider.getClassByHash(classHash);
console.log("constructor =", compiledSierra.abi.find((item) => item.type == "constructor"));
```

**Devnet version**

- I am using Devnet version: 0.4.2
- I have found that this issue is not present in Devnet version:

**System specifications**

- OS: Linux Mint

### PR DESCRIPTION
**Pull request by FabijanC**
## Usage related changes

- Close #795
- Minting now updates the `total_supply` property of token contracts.
- Return RPC error on failed minting.

## Development related changes

- Rely on `permissioned_mint` instead of `transfer` for minting.
- Remove unused minting error variant.
- Prevent overflow in token contract `total_supply` in case of forking.

## Checklist:

- [x] Checked out the [contribution guidelines](https://github.com/0xSpaceShard/starknet-devnet/blob/main/.github/CONTRIBUTING.md)
- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] No unused dependencies - `./scripts/check_unused_deps.sh`
- [x] No spelling errors - `./scripts/check_spelling.sh`
- [x] Performed code self-review
- [x] Rebased to the latest commit of the target branch (or merged it into my branch)
    -   Once you make the PR reviewable, please avoid force-pushing
- [x] Updated the docs if needed - `./website/README.md`
- [x] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet/issues) resolvable by this PR - [linking info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [x] Updated the tests if needed; all passing - [execution info](https://github.com/0xSpaceShard/starknet-devnet/blob/main/.github/CONTRIBUTING.md#test-execution)

## Summary by CodeRabbit

- **New Features**
  - Added distinct ETH and STRK ERC20 token contracts, each with unique class hashes, addresses, names, and symbols.
  - Improved error reporting for minting failures, providing transaction hash and revert reason when minting is reverted.

- **Bug Fixes**
  - Ensured correct function selector is used for minting operations and transaction traces.
  - Prevented redeployment of accounts if already deployed.

- **Documentation**
  - Updated documentation to describe error responses for reverted minting transactions and clarified various comments.

- **Chores**
  - Refined and updated constants and test configurations to use the new ETH and STRK ERC20 contract details.
  - Removed obsolete constants and error variants.

### CODE REVIEW

File: crates/starknet-devnet-core/src/state/mod.rs [hunk 1]
```diff
@@ -50,12 +50,13 @@ pub trait CustomState {
         contract_class: ContractClass,
     ) -> DevnetResult<()>;
 
-    /// Link contract address to class hash
-    fn predeploy_contract(
+    /// Link contract address to class hash. Does not include balance modification or constructor
+    /// simulation. Returns `true` if deployment was performed by this method, `false` otherwise.
+    fn predeploy_if_undeployed(
```
Comment (FabijanC) [inline crates/starknet-devnet-core/src/state/mod.rs:55]: Consider reverting this rename

Comment (FabijanC) [reply crates/starknet-devnet-core/src/state/mod.rs]: https://github.com/0xSpaceShard/starknet-devnet/pull/799/commits/dee7d572cd0297e6a516f747168c478c1026348b
