### PR TITLE
Fix port acquisition in BackgroundAnvil

### LINKED ISSUE #670: BackgroundAnvil should use the same spawn check as BackgroundDevnet
Current logic: https://github.com/0xSpaceShard/starknet-devnet-rs/blob/d37b4fccee3eec4f696d799f1d605f3c0755f446/crates/starknet-devnet/tests/common/background_anvil.rs#L57

Should be as implemented for BackgroundDevnet in https://github.com/0xSpaceShard/starknet-devnet-rs/pull/669. This includes relying on random port acquisition with `--port 0` instead of randomly guessing.
Perhaps common logic can be extracted.

### PR DESCRIPTION
**Pull request by FabijanC**
## Usage related changes

- Close #670 

## Development related changes

- Improve formatting
- Remove redundant clippy ignores
- Expand use of `anyhow::anyhow!` macro

## Checklist:

- [x] Checked out the [contribution guidelines](CONTRIBUTING.md)
- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] No unused dependencies - `./scripts/check_unused_deps.sh`
- [x] No spelling errors - `./scripts/check_spelling.sh`
- [x] Performed code self-review
- [x] Rebased to the latest commit of the target branch (or merged it into my branch)
    -   Once you make the PR reviewable, please avoid force-pushing
- [x] Updated the docs if needed - `./website/README.md`
- [x] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) resolvable by this PR - [linking info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [x] Updated the tests if needed; all passing - [execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/main/.github/CONTRIBUTING.md#test-execution)

## Summary by CodeRabbit

- **Bug Fixes**
  - Corrected a minor typographical error in internal messaging.

- **Refactor**
  - Streamlined the process for selecting available ports.
  - Improved error handling and messaging for unresponsive background processes.

- **Tests**
  - Enhanced integration testing utilities for clearer diagnostic feedback and more robust process monitoring.

### CODE REVIEW

File: tests/integration/common/background_anvil.rs [hunk 1]
```diff
@@ -65,34 +63,30 @@ impl BackgroundAnvil {
...
     pub async fn deploy_l1l2_contract(
         &self,
         messaging_address: Address,
     ) -> Result<Address, TestError> {
-        let contract = abigen::L1L2Example::deploy(
-            self.provider_signer.clone(),
-            messaging_address,
-        )
+        // Required by the new version of anvil, as default is no longer accepted.
+        // We use here the default value from anvil and hardat multiplied by 2.
```
Comment (marioiordanov) [inline tests/integration/common/background_anvil.rs:77]: typo hardhat

Comment (FabijanC) [reply tests/integration/common/background_anvil.rs]: It's an old typo, it was also present in another place; addressed in https://github.com/0xSpaceShard/starknet-devnet/pull/708/commits/997c64604a0d46eb31b5bbfe6fe2adb77ff5ad48

**Review by marioiordanov — APPROVED** [review]
